version: "3"
services:
  servidor:
    build: 
      context: ./servidor
      dockerfile: Dockerfile
    volumes:
      - ./servidor:/app/
    command: python /servidor/servidor.py
    network_mode: host
    ports:
      - 5000:5000
  cliente:
    build: 
      context: ./cliente
      dockerfile: Dockerfile
    volumes:
      - ./cliente:/app/
    network_mode: host
    command: python /cliente/cliente.py
    ports:
      - 5000:5000
    volumes:
      - ./cliente:/app/
    depends_on:
      - servidor