version: "3"
services:
  servidor:
    build: 
      context: ./servidor
      dockerfile: Dockerfile
    volumes:
      - ./servidor:/app/
    command: python servidor.py
    network_mode: host
    ports:
      - 5000-5004:5000-5004
    depends_on:
      - nodo1
  cliente:
    build: 
      context: ./cliente
      dockerfile: Dockerfile
    volumes:
      - ./cliente:/app/
    network_mode: host
    command: python /cliente/cliente.py
    ports:
      - 5000:5000
    volumes:
      - ./cliente:/app/
    depends_on:
      - servidor
  nodo1:
    build: 
      context: ./nodo1
      dockerfile: Dockerfile
    volumes:
      - ./nodo1:/app/
    network_mode: host
    command: python /nodo1/nodo1.py
    ports:
      - 5001:5001
    volumes:
      - ./nodo1:/app/
