version: "3"
services:
  servidor:
    build: 
      context: ./servidor
      dockerfile: Dockerfile
    volumes:
      - ./servidor:/app/
    command: python servidor.py
    network_mode: host
    ports:
      - 5000-5007:5000-5007
    depends_on:
      - nodo1
      - nodo2
      - nodo3
  cliente:
    build: 
      context: ./cliente
      dockerfile: Dockerfile
    volumes:
      - ./cliente:/app/
    network_mode: host
    command: python /cliente/cliente.py
    ports:
      - 5000:5000
    volumes:
      - ./cliente:/app/
    depends_on:
      - servidor
  nodo1:
    build: 
      context: ./nodo1
      dockerfile: Dockerfile
    volumes:
      - ./nodo1:/app/
    network_mode: host
    command: python /nodo1/nodo1.py
    ports:
      - 5001:5001
    volumes:
      - ./nodo1:/app/
  nodo2:
    build: 
      context: ./nodo2
      dockerfile: Dockerfile
    volumes:
      - ./nodo2:/app/
    network_mode: host
    command: python /nodo2/nodo2.py
    ports:
      - 5002:5002
    volumes:
      - ./nodo2:/app/
  nodo3:
    build: 
      context: ./nodo3
      dockerfile: Dockerfile
    volumes:
      - ./nodo3:/app/
    network_mode: host
    command: python /nodo3/nodo3.py
    ports:
      - 5003:5003
    volumes:
      - ./nodo3:/app/