version: "3"
services:

  servidor:
    build: servidor/
    command: python ./servidor.py
    ports:
      - 5000:5000
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5007:5007
      
  cliente:
    build: cliente/
    command: python ./cliente.py
    network_mode: host
    ports:
      - 5000:5000
    depends_on:
      - servidor

  nodo1:
    build: nodo1/
    command: python ./nodo1.py
    network_mode: host
    ports:
      - 5001:5001
      - 5007:5007

  nodo2:
    build: nodo2/
    command: python ./nodo2.py
    network_mode: host
    ports:
      - 5002:5002
      - 5007:5007

  nodo3:
    build: nodo3/
    command: python ./nodo3.py
    network_mode: host
    ports:
      - 5003:5003
      - 5007:5007

